### ISSUE TITLE
AltGr+n issue and resolution

### ISSUE THREAD

**Issue by mabasic** [skuroda/Sublime-AdvancedNewFile#136]
I'm having issues with AltGr+n keymap binding.

Whenever I click `AltGr+n` it invokes this `{ "keys": ["ctrl+alt+n"], "command": "advanced_new_file_new"},` but that key combo on my keyboard usually closes `}`. As you can imagine it is very frustrating to not be able to close the brackets.

I have found the solution:
- Install `Package​Resource​Viewer`
- Extract `AdvancedNewFile`
- Open `Default (Windows).sublime-keymap`
- Change line `{ "keys": ["ctrl+alt+n"], "command": "advanced_new_file_new"},` to `{ "keys": ["ctrl+n"], "command": "advanced_new_file_new"},`

If I place the above keymap in my user keymap file it does not work for some reason.

Now it works, but could you just delete that binding and let people add it if needed?

**Comment by skuroda** [comment]
Hi, unfortunately I won't be removing the behavior as it's the established default. The key bindings that are there now were part of the plugin when I inherited it. As to not break it for any existing users, I chose to leave it in. All the new commands I have added do not include a default key binding. I'm glad you found the solution leveraging the override functionality. 

If I may make a suggestion though, rather than extracting the entire package, simply open the key binding file using PackageResourceViewer. Then, edit the keybinding file and save. When the file is saved, it will place it in the appropriate location to override the packaged file. This will allow you to uptake new functionality and bug fixes when they are pushed. If you extract the entire file, you won't receive these updates.

Thank you for using AdvancedNewFile (and PackageResourceViewer)!

**Comment by FichteFoll** [comment]
Instead of changing default files (using PackageResourceViewer), it is usually better to re-override things whenever possile. For keybindings, this would be inside your user keybindings.

The reason is that if there ever are changes to the file in the package the changes will not go through, you will not notice and not be notified.
