### ISSUE TITLE
Adding a forward slash to the end of a directory name when creating a new file

### ISSUE THREAD

**Issue by mbigras** [skuroda/Sublime-AdvancedNewFile#158]
As it stands right now when creating a new file with `super + n` the directory is autocompleted without the forward slash `/`  as shown below:
![Imgur](http://i.imgur.com/qhr9WbY.png)

Is it possible to change the autocompletion so it adds the `/`, also shown below:
![Imgur](http://i.imgur.com/LEjWvrS.png)

This is useful for at least a couple reasons:
1. you can keep on typing the next directory quickly
2. you know that the autocompletion is in fact a directory and not a file.

Also, thank you for such an amazing plugin, I love using it more and more every day :)

**Comment by skuroda** [comment]
It should add the slash if there are no other options when doing the tab autocomplete. However, if there are other options it will not, as it will cycle through them. In your example. if you did `to<tab>` it would cycle through the options. Whereas `tor<tab>` would append the slash (assuming nothing below the view contains the prefix "tor"). This is similar to what you would see in the shell, though it would list all the possible directories rather than cycling through them. Is that the behavior you are seeing? If not there may be a bug in the autocomplete logic.
